(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(connection-local-profile-alist
   '((tramp-flatpak-connection-local-default-profile
      (tramp-remote-path "/app/bin" tramp-default-remote-path "/bin" "/usr/bin"
       "/sbin" "/usr/sbin" "/usr/local/bin" "/usr/local/sbin" "/local/bin"
       "/local/freeware/bin" "/local/gnu/bin" "/usr/freeware/bin" "/usr/pkg/bin"
       "/usr/contrib/bin" "/opt/bin" "/opt/sbin" "/opt/local/bin"))
     (tramp-kubernetes-connection-local-default-profile
      (tramp-config-check . tramp-kubernetes--current-context-data)
      (tramp-extra-expand-args 97
                               (tramp-kubernetes--container
                                (car tramp-current-connection))
                               104
                               (tramp-kubernetes--pod
                                (car tramp-current-connection))
                               120
                               (tramp-kubernetes--context-namespace
                                (car tramp-current-connection))))
     (tramp-container-connection-local-default-flatpak-profile
      (tramp-remote-path "/app/bin" tramp-default-remote-path "/bin" "/usr/bin"
                         "/sbin" "/usr/sbin" "/usr/local/bin" "/usr/local/sbin"
                         "/local/bin" "/local/freeware/bin" "/local/gnu/bin"
                         "/usr/freeware/bin" "/usr/pkg/bin" "/usr/contrib/bin"
                         "/opt/bin" "/opt/sbin" "/opt/local/bin"))
     (eshell-connection-default-profile (eshell-path-env-list))
     (tramp-connection-local-darwin-ps-profile
      (tramp-process-attributes-ps-args "-acxww" "-o"
                                        "pid,uid,user,gid,comm=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
                                        "-o" "state=abcde" "-o"
                                        "ppid,pgid,sess,tty,tpgid,minflt,majflt,time,pri,nice,vsz,rss,etime,pcpu,pmem,args")
      (tramp-process-attributes-ps-format (pid . number) (euid . number)
                                          (user . string) (egid . number)
                                          (comm . 52) (state . 5)
                                          (ppid . number) (pgrp . number)
                                          (sess . number) (ttname . string)
                                          (tpgid . number) (minflt . number)
                                          (majflt . number)
                                          (time . tramp-ps-time) (pri . number)
                                          (nice . number) (vsize . number)
                                          (rss . number) (etime . tramp-ps-time)
                                          (pcpu . number) (pmem . number) (args)))
     (tramp-connection-local-busybox-ps-profile
      (tramp-process-attributes-ps-args "-o"
                                        "pid,user,group,comm=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
                                        "-o" "stat=abcde" "-o"
                                        "ppid,pgid,tty,time,nice,etime,args")
      (tramp-process-attributes-ps-format (pid . number) (user . string)
                                          (group . string) (comm . 52)
                                          (state . 5) (ppid . number)
                                          (pgrp . number) (ttname . string)
                                          (time . tramp-ps-time) (nice . number)
                                          (etime . tramp-ps-time) (args)))
     (tramp-connection-local-bsd-ps-profile
      (tramp-process-attributes-ps-args "-acxww" "-o"
                                        "pid,euid,user,egid,egroup,comm=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
                                        "-o"
                                        "state,ppid,pgid,sid,tty,tpgid,minflt,majflt,time,pri,nice,vsz,rss,etimes,pcpu,pmem,args")
      (tramp-process-attributes-ps-format (pid . number) (euid . number)
                                          (user . string) (egid . number)
                                          (group . string) (comm . 52)
                                          (state . string) (ppid . number)
                                          (pgrp . number) (sess . number)
                                          (ttname . string) (tpgid . number)
                                          (minflt . number) (majflt . number)
                                          (time . tramp-ps-time) (pri . number)
                                          (nice . number) (vsize . number)
                                          (rss . number) (etime . number)
                                          (pcpu . number) (pmem . number) (args)))
     (tramp-connection-local-default-shell-profile (shell-file-name . "/bin/sh")
      (shell-command-switch . "-c"))
     (tramp-connection-local-default-system-profile (path-separator . ":")
      (null-device . "/dev/null"))))
 '(custom-safe-themes
   '("e1df746a4fa8ab920aafb96c39cd0ab0f1bac558eff34532f453bd32c687b9d6"
     "21d2bf8d4d1df4859ff94422b5e41f6f2eeff14dd12f01428fa3cb4cb50ea0fb"
     "5ec088e25ddfcfe37b6ae7712c9cb37fd283ea5df7ac609d007cafa27dab6c64"
     "d43860349c9f7a5b96a090ecf5f698ff23a8eb49cd1e5c8a83bb2068f24ea563"
     "0f220ea77c6355c411508e71225680ecb3e308b4858ef6c8326089d9ea94b86f"
     "9d5124bef86c2348d7d4774ca384ae7b6027ff7f6eb3c401378e298ce605f83a"
     "8c7e832be864674c220f9a9361c851917a93f921fedb7717b1b5ece47690c098"
     "4b6cc3b60871e2f4f9a026a5c86df27905fb1b0e96277ff18a76a39ca53b82e1"
     "0325a6b5eea7e5febae709dab35ec8648908af12cf2d2b569bedc8da0a3a81c1"
     "5c7720c63b729140ed88cf35413f36c728ab7c70f8cd8422d9ee1cedeb618de5"
     "88f7ee5594021c60a4a6a1c275614103de8c1435d6d08cc58882f920e0cec65e"
     "7964b513f8a2bb14803e717e0ac0123f100fb92160dcf4a467f530868ebaae3e"
     "afa47084cb0beb684281f480aa84dab7c9170b084423c7f87ba755b15f6776ef"
     "51c71bb27bdab69b505d9bf71c99864051b37ac3de531d91fdad1598ad247138"
     "02f57ef0a20b7f61adce51445b68b2a7e832648ce2e7efb19d217b6454c1b644" default))
 '(ignored-local-variable-values
   '((flycheck-checker . golangci-lint) (comment-fill-column . 80)))
 '(magit-todos-insert-after '(bottom) nil nil "Changed by setter of obsolete option `magit-todos-insert-at'")
 '(org-agenda-files
   '("~/Documents/org-roam/sites/app.asana.com/0/home/1209741931132787/1209850466363366.org"
     "/Users/gregory.ganley/Documents/org-roam/daily/2025.org"
     "/Users/gregory.ganley/org-roam/todo.org"
     "/Users/gregory.ganley/Developer/devops/clusters/cluster-bootstrapper/todo.org"
     "/Users/gregory.ganley/Developer/devops/devops-firewalk/todo.org"
     "/Users/gregory.ganley/Documents/org-roam/capture/scs_migration.org"
     "/Users/gregory.ganley/Documents/org-roam/daily/2024.org"
     "/Users/gregory.ganley/Documents/org-roam/todo.org"
     "/Users/gregory.ganley/org-roam/daily/2023.org"
     "/Users/gregory.ganley/org-roam/capture/20210330153550-mysql_to_rds_transition.org"
     "/Users/gregory.ganley/org-roam/capture/20210330192155-alex.org"
     "/Users/gregory.ganley/org-roam/capture/20210330192249-andrew_miller.org"
     "/Users/gregory.ganley/org-roam/capture/20210331091207-devops_initiatives.org"
     "/Users/gregory.ganley/org-roam/capture/2021_yearly_goal.org"
     "/Users/gregory.ganley/org-roam/capture/alertmanager.org"
     "/Users/gregory.ganley/org-roam/capture/alex_wiggins.org"
     "/Users/gregory.ganley/org-roam/capture/andrew_miller.org"
     "/Users/gregory.ganley/org-roam/capture/aws_iam.org"
     "/Users/gregory.ganley/org-roam/capture/beverly_boydston.org"
     "/Users/gregory.ganley/org-roam/capture/branching_strat.org"
     "/Users/gregory.ganley/org-roam/capture/break.org"
     "/Users/gregory.ganley/org-roam/capture/brian_agbay.org"
     "/Users/gregory.ganley/org-roam/capture/car_insurance.org"
     "/Users/gregory.ganley/org-roam/capture/chef_notes_with_alex.org"
     "/Users/gregory.ganley/org-roam/capture/christopher_morrow.org"
     "/Users/gregory.ganley/org-roam/capture/cloud_team.org"
     "/Users/gregory.ganley/org-roam/capture/d_d.org"
     "/Users/gregory.ganley/org-roam/capture/dnd_char.org"
     "/Users/gregory.ganley/org-roam/capture/ducksauce.org"
     "/Users/gregory.ganley/org-roam/capture/dumbcodenames.org"
     "/Users/gregory.ganley/org-roam/capture/emacs.org"
     "/Users/gregory.ganley/org-roam/capture/gift_ideas.org"
     "/Users/gregory.ganley/org-roam/capture/git.org"
     "/Users/gregory.ganley/org-roam/capture/info.org"
     "/Users/gregory.ganley/org-roam/capture/interview_questions.org"
     "/Users/gregory.ganley/org-roam/capture/invictus.org"
     "/Users/gregory.ganley/org-roam/capture/jira_to_gitlab.org"
     "/Users/gregory.ganley/org-roam/capture/k8s_deployment_process.org"
     "/Users/gregory.ganley/org-roam/capture/khoa_tran.org"
     "/Users/gregory.ganley/org-roam/capture/lunch.org"
     "/Users/gregory.ganley/org-roam/capture/melee.org"
     "/Users/gregory.ganley/org-roam/capture/morning.org"
     "/Users/gregory.ganley/org-roam/capture/move_serverless_to_gitlab.org"
     "/Users/gregory.ganley/org-roam/capture/mox_campaign.org"
     "/Users/gregory.ganley/org-roam/capture/nels.org"
     "/Users/gregory.ganley/org-roam/capture/nels_oscar.org"
     "/Users/gregory.ganley/org-roam/capture/one_liners.org"
     "/Users/gregory.ganley/org-roam/capture/project_program.org"
     "/Users/gregory.ganley/org-roam/capture/reading.org"
     "/Users/gregory.ganley/org-roam/capture/reading_list.org"
     "/Users/gregory.ganley/org-roam/capture/righeous_folly.org"
     "/Users/gregory.ganley/org-roam/capture/slack.org"
     "/Users/gregory.ganley/org-roam/capture/standard_kubernetes_deployment.org"
     "/Users/gregory.ganley/org-roam/capture/tattoo.org"
     "/Users/gregory.ganley/org-roam/capture/test.org"
     "/Users/gregory.ganley/org-roam/capture/verum_schedule.org"
     "/Users/gregory.ganley/org-roam/capture/work_log.org"
     "/Users/gregory.ganley/org-roam/capture/xlink_sf_support.org"
     "/Users/gregory.ganley/org-roam/ref/aws_cloudwatch_grafana_labs.org"
     "/Users/gregory.ganley/org-roam/ref/browse_server_rms_savant_bitbucket_server.org"
     "/Users/gregory.ganley/org-roam/ref/building_and_publishing_a_container_image_with_gitlab_ci_and_kaniko_by_a_kadir_mutlu_medium.org"
     "/Users/gregory.ganley/org-roam/ref/chef_enabling_the_coded_enterprise_through_infrastructure_security_and_application_automation.org"
     "/Users/gregory.ganley/org-roam/ref/cloud_infrastructure_admin_workstation_setup_engineering_savant_confluence_wiki.org"
     "/Users/gregory.ganley/org-roam/ref/comparison_to_alternatives_prometheus.org"
     "/Users/gregory.ganley/org-roam/ref/golang_samples_list_gcs_objects_go_at_master_googlecloudplatform_golang_samples.org"
     "/Users/gregory.ganley/org-roam/ref/grafana_mysql_database.org"
     "/Users/gregory.ganley/org-roam/ref/move_to_managed_databases_migrate_from_mysql_to_amazon_rds_youtube.org"
     "/Users/gregory.ganley/org-roam/ref/mysql_mysqldump_throws_unknown_table_column_statistics_in_information_schema_1109_server_fault.org"
     "/Users/gregory.ganley/org-roam/ref/org_roam_user_manual.org"
     "/Users/gregory.ganley/org-roam/ref/overview_prometheus.org"
     "/Users/gregory.ganley/org-roam/ref/racepoint_energy_serverless_rcl_gitlab.org"
     "/Users/gregory.ganley/org-roam/ref/racepoint_energy_website_sitespark_gitlab.org"
     "/Users/gregory.ganley/org-roam/ref/storybook_ui_component_explorer_for_frontend_developers.org"
     "/Users/gregory.ganley/org-roam/ref/use_kaniko_to_build_docker_images_gitlab.org"
     "/Users/gregory.ganley/org-roam/ref/website_gitlab.org"
     "/Users/gregory.ganley/org-roam/sites/about.gitlab.com/handbook/marketing/strategic-marketing/roles-personas/devon-devops-engineer.org"
     "/Users/gregory.ganley/org-roam/sites/about.gitlab.com/pricing/saas/feature-comparison.org"
     "/Users/gregory.ganley/org-roam/sites/amzn.github.io/ion-docs.org"
     "/Users/gregory.ganley/org-roam/sites/aws.amazon.com/blogs/compute/managing-secrets-for-amazon-ecs-applications-using-parameter-store-and-iam-roles-for-tasks.org"
     "/Users/gregory.ganley/org-roam/sites/aws.amazon.com/blogs/database/readable-standby-instances-in-amazon-rds-multi-az-deployments-a-new-high-availability-option.org"
     "/Users/gregory.ganley/org-roam/sites/aws.amazon.com/blogs/security/how-to-use-trust-policies-with-iam-roles.org"
     "/Users/gregory.ganley/org-roam/sites/aws.amazon.com/kinesis/data-firehose.org"
     "/Users/gregory.ganley/org-roam/sites/aws.amazon.com/sns/whats-new-cards.sort-byitem.additionalFields.postDateTime&whats-new-cards.sort-orderdesc.org"
     "/Users/gregory.ganley/org-roam/sites/aws.amazon.com/chatbot.org"
     "/Users/gregory.ganley/org-roam/sites/aws.amazon.com/kms.org"
     "/Users/gregory.ganley/org-roam/sites/aws.amazon.com/rds.org"
     "/Users/gregory.ganley/org-roam/sites/aws.github.io/aws-eks-best-practices/security/docs/iam.org"
     "/Users/gregory.ganley/org-roam/sites/aws.github.io/aws-sdk-go-v2/docs/sdk-utilities/s3/#unseekable-streaming-input.org"
     "/Users/gregory.ganley/org-roam/sites/cloud.google.com/storage.org"
     "/Users/gregory.ganley/org-roam/sites/code.visualstudio.com/updates/v1_58.org"
     "/Users/gregory.ganley/org-roam/sites/console.aws.amazon.com/billing/home?#/preferences.org"
     "/Users/gregory.ganley/org-roam/sites/discourse.haproxy.org/t/docker-image-of-haproxy-latest-seems-doesnt-like-http-use-htx/7261.org"
     "/Users/gregory.ganley/org-roam/sites/docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-protect-stacks.org"
     "/Users/gregory.ganley/org-roam/sites/docs.aws.amazon.com/AWSEC2/latest/UserGuide/recognize-expanded-volume-linux.org"
     "/Users/gregory.ganley/org-roam/sites/docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/monitor_estimated_charges_with_cloudwatch.html#turning_on_billing_metrics.org"
     "/Users/gregory.ganley/org-roam/sites/docs.aws.amazon.com/AmazonECS/latest/userguide/task-iam-roles.org"
     "/Users/gregory.ganley/org-roam/sites/docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Tutorials.RestoringFromSnapshot.org"
     "/Users/gregory.ganley/org-roam/sites/docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.Encryption.Keys.org"
     "/Users/gregory.ganley/org-roam/sites/docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.Encryption.org"
     "/Users/gregory.ganley/org-roam/sites/docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ReadRepl.org"
     "/Users/gregory.ganley/org-roam/sites/docs.aws.amazon.com/IAM/latest/UserGuide/id.org"
     "/Users/gregory.ganley/org-roam/sites/docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_ExportTableToPointInTime.org"
     "/Users/gregory.ganley/org-roam/sites/docs.aws.amazon.com/amazondynamodb/latest/developerguide/DataExport.org"
     "/Users/gregory.ganley/org-roam/sites/docs.aws.amazon.com/chatbot/latest/adminguide/what-is.org"
     "/Users/gregory.ganley/org-roam/sites/docs.aws.amazon.com/eks/latest/userguide/associate-service-account-role.org"
     "/Users/gregory.ganley/org-roam/sites/docs.aws.amazon.com/eks/latest/userguide/pod-networking.org"
     "/Users/gregory.ganley/org-roam/sites/docs.aws.amazon.com/kms/latest/developerguide/concepts.org"
     "/Users/gregory.ganley/org-roam/sites/docs.aws.amazon.com/quicksight/latest/user/regions.org"
     "/Users/gregory.ganley/org-roam/sites/docs.aws.amazon.com/quicksight/latest/user/working-with-aws-vpc.org"
     "/Users/gregory.ganley/org-roam/sites/docs.aws.amazon.com/secretsmanager/latest/userguide/integrating_csi_driver.org"
     "/Users/gregory.ganley/org-roam/sites/docs.aws.amazon.com/vpc/latest/ipam/what-it-is-ipam.org"
     "/Users/gregory.ganley/org-roam/sites/docs.aws.amazon.com/amazon_eks_cluster_iam_role_amazon_eks.org"
     "/Users/gregory.ganley/org-roam/sites/docs.aws.amazon.com/best_practices_for_aws_database_migration_service_aws_database_migration_service.org"
     "/Users/gregory.ganley/org-roam/sites/docs.aws.amazon.com/exporting_db_snapshot_data_to_amazon_s3.org"
     "/Users/gregory.ganley/org-roam/sites/docs.aws.amazon.com/getting_cloudwatch_events_and_amazon_eventbridge_events_for_amazon_rds_amazon_relational_database_service.org"
     "/Users/gregory.ganley/org-roam/sites/docs.aws.amazon.com/high_level_view_of_aws_dms_aws_database_migration_service.org"
     "/Users/gregory.ganley/org-roam/sites/docs.aws.amazon.com/overview_of_monitoring_amazon_rds_amazon_relational_database_service.org"
     "/Users/gregory.ganley/org-roam/sites/docs.aws.amazon.com/rds_amazon_web_services_go_sdk.org"
     "/Users/gregory.ganley/org-roam/sites/docs.aws.amazon.com/replicating_automated_backups_to_another_aws_region_amazon_relational_database_service.org"
     "/Users/gregory.ganley/org-roam/sites/docs.aws.amazon.com/tutorial_run_an_amazon_ecs_task_when_a_file_is_uploaded_to_an_amazon_s3_bucket_amazon_cloudwatch_events.org"
     "/Users/gregory.ganley/org-roam/sites/docs.aws.amazon.com/using_a_mysql_compatible_database_as_a_source_for_aws_dms_aws_database_migration_service.org"
     "/Users/gregory.ganley/org-roam/sites/docs.aws.amazon.com/using_amazon_ecr_images_with_amazon_ecs_amazon_ecr.org"
     "/Users/gregory.ganley/org-roam/sites/docs.aws.amazon.com/using_amazon_ecr_with_the_aws_cli_amazon_ecr.org"
     "/Users/gregory.ganley/org-roam/sites/docs.bazel.build/versions/4.2.1/build-ref.org"
     "/Users/gregory.ganley/org-roam/sites/docs.fluentbit.io/manual/installation/kubernetes.org"
     "/Users/gregory.ganley/org-roam/sites/docs.gitlab.com/ee/administration/terraform_state.org"
     "/Users/gregory.ganley/org-roam/sites/docs.gitlab.com/ee/api/protected_environments.org"
     "/Users/gregory.ganley/org-roam/sites/docs.gitlab.com/ee/ci/environments/deployment_safety.org"
     "/Users/gregory.ganley/org-roam/sites/docs.gitlab.com/ee/ci/examples/semantic-release.org"
     "/Users/gregory.ganley/org-roam/sites/docs.gitlab.com/ee/ci/yaml/#artifact-downloads-with-needs.org"
     "/Users/gregory.ganley/org-roam/sites/docs.gitlab.com/ee/ci/yaml/index.html#release.org"
     "/Users/gregory.ganley/org-roam/sites/docs.gitlab.com/ee/integration/jira/issues.html#view-jira-issues.org"
     "/Users/gregory.ganley/org-roam/sites/docs.gitlab.com/ee/user/analytics/code_review_analytics.org"
     "/Users/gregory.ganley/org-roam/sites/docs.gitlab.com/ee/user/analytics/productivity_analytics.org"
     "/Users/gregory.ganley/org-roam/sites/docs.gitlab.com/ee/user/infrastructure/mr_integration.org"
     "/Users/gregory.ganley/org-roam/sites/docs.gitlab.com/ee/user/infrastructure/terraform_state.org"
     "/Users/gregory.ganley/org-roam/sites/docs.gitlab.com/ee/user/packages/npm_registry/index.html#publish-an-npm-package-by-using-cicd.org"
     "/Users/gregory.ganley/org-roam/sites/docs.gitlab.com/ee/user/packages/container_registry.org"
     "/Users/gregory.ganley/org-roam/sites/docs.gitlab.com/ee/user/project/clusters/serverless/aws.org"
     "/Users/gregory.ganley/org-roam/sites/docs.gitlab.com/ee/user/project/deploy_tokens/#read-container-registry-images.org"
     "/Users/gregory.ganley/org-roam/sites/docs.gitlab.com/ee/user/project/issues/multiple_assignees_for_issues.org"
     "/Users/gregory.ganley/org-roam/sites/docs.gitlab.com/ee/user/project/merge_requests/merge_request_dependencies.org"
     "/Users/gregory.ganley/org-roam/sites/docs.gitlab.com/ee/user/project/releases/#add-release-notes-to-git-tags.org"
     "/Users/gregory.ganley/org-roam/sites/docs.gitlab.com/ee/user/project/releases/index.org"
     "/Users/gregory.ganley/org-roam/sites/docs.gitlab.com/ee/user/project/code_owners.org"
     "/Users/gregory.ganley/org-roam/sites/dominik-tornow.medium.com/the-mechanics-of-kubernetes-ac8112eaa302.org"
     "/Users/gregory.ganley/org-roam/sites/en.wikipedia.org/wiki/CNAME_record.org"
     "/Users/gregory.ganley/org-roam/sites/en.wikipedia.org/wiki/CPU_timeSubdivision.org"
     "/Users/gregory.ganley/org-roam/sites/en.wikipedia.org/wiki/Certificate_authority.org"
     "/Users/gregory.ganley/org-roam/sites/en.wikipedia.org/wiki/Iptables.org"
     "/Users/gregory.ganley/org-roam/sites/en.wikipedia.org/wiki/Just_culture.org"
     "/Users/gregory.ganley/org-roam/sites/en.wikipedia.org/wiki/Linux_namespaces.org"
     "/Users/gregory.ganley/org-roam/sites/en.wikipedia.org/wiki/Mutual_authentication#mTLS.org"
     "/Users/gregory.ganley/org-roam/sites/en.wikipedia.org/wiki/OSI_protocols.org"
     "/Users/gregory.ganley/org-roam/sites/en.wikipedia.org/wiki/Public_key_infrastructure.org"
     "/Users/gregory.ganley/org-roam/sites/en.wikipedia.org/wiki/Role-based_access_control.org"
     "/Users/gregory.ganley/org-roam/sites/en.wikipedia.org/wiki/SPDY.org"
     "/Users/gregory.ganley/org-roam/sites/english.stackexchange.com/questions/28310/origin-of-ballpark-estimate-to-mean-a-very-rough-estimate.org"
     "/Users/gregory.ganley/org-roam/sites/etcd.io/index.org"
     "/Users/gregory.ganley/org-roam/sites/gelighting.atlassian.net/browse/CLIP-12.org"
     "/Users/gregory.ganley/org-roam/sites/gelighting.atlassian.net/browse/CLIP-14.org"
     "/Users/gregory.ganley/org-roam/sites/gelighting.atlassian.net/browse/CLIP-15.org"
     "/Users/gregory.ganley/org-roam/sites/gelighting.atlassian.net/browse/CORE-3916.org"
     "/Users/gregory.ganley/org-roam/sites/gelighting.atlassian.net/browse/CORE-4084.org"
     "/Users/gregory.ganley/org-roam/sites/gelighting.atlassian.net/browse/SCD-40.org"
     "/Users/gregory.ganley/org-roam/sites/gelighting.atlassian.net/browse/SCD-41.org"
     "/Users/gregory.ganley/org-roam/sites/gelighting.atlassian.net/browse/SCD-43.org"
     "/Users/gregory.ganley/org-roam/sites/gelighting.atlassian.net/browse/SCD-44.org"
     "/Users/gregory.ganley/org-roam/sites/gelighting.atlassian.net/browse/SCD-45.org"
     "/Users/gregory.ganley/org-roam/sites/gelighting.atlassian.net/browse/SCD-46.org"
     "/Users/gregory.ganley/org-roam/sites/gelighting.atlassian.net/browse/SI-21363.org"
     "/Users/gregory.ganley/org-roam/sites/gelighting.atlassian.net/browse/SW-315.org"
     "/Users/gregory.ganley/org-roam/sites/gelighting.atlassian.net/browse/SW-94.org"
     "/Users/gregory.ganley/org-roam/sites/gelighting.atlassian.net/browse/WS-2292.org"
     "/Users/gregory.ganley/org-roam/sites/gelighting.atlassian.net/browse/scd_40_move_from_ec2_mysql_to_rds_mysql_ge_lighting_jira.org"
     "/Users/gregory.ganley/org-roam/sites/gelighting.atlassian.net/browse/scd_42_research_replacement_solution_for_sensu_which_has_now_been_eol_ge_lighting_jira.org"
     "/Users/gregory.ganley/org-roam/sites/gelighting.atlassian.net/browse/scd_47_all_serverless_deployments_should_be_upgraded_to_node_14_x_ge_lighting_jira.org"
     "/Users/gregory.ganley/org-roam/sites/gelighting.atlassian.net/browse/scd_49_bring_up_video_ai_service_on_ec2_instance_ge_lighting_jira.org"
     "/Users/gregory.ganley/org-roam/sites/gerrit.wikimedia.org/r/plugins/gitiles/format.org"
     "/Users/gregory.ganley/org-roam/sites/git.cs.savantsystems.com/projects/OPS/repos/chef-repo/pull-requests/26/overview.org"
     "/Users/gregory.ganley/org-roam/sites/git.cs.savantsystems.com/projects/SRV/repos/ems/browse.org"
     "/Users/gregory.ganley/org-roam/sites/github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.mdexemplars.org"
     "/Users/gregory.ganley/org-roam/sites/github.com/PRQL/prql.org"
     "/Users/gregory.ganley/org-roam/sites/github.com/flannel-io/flannel.org"
     "/Users/gregory.ganley/org-roam/sites/github.com/google/mtail.org"
     "/Users/gregory.ganley/org-roam/sites/github.com/hlissner/doom-emacs/blob/develop/docs/getting_started.org#configure.org"
     "/Users/gregory.ganley/org-roam/sites/github.com/istio/istio/tree/master/manifests/addons/dashboards.org"
     "/Users/gregory.ganley/org-roam/sites/github.com/jkroepke/helm-secrets.org"
     "/Users/gregory.ganley/org-roam/sites/github.com/kubernetes/ingress-nginx.org"
     "/Users/gregory.ganley/org-roam/sites/github.com/kubernetes/kube-state-metrics.org"
     "/Users/gregory.ganley/org-roam/sites/github.com/maxbube/mydumper.org"
     "/Users/gregory.ganley/org-roam/sites/github.com/org-roam/org-roam/blob/v2/doc/org-roam.org.org"
     "/Users/gregory.ganley/org-roam/sites/github.com/projectcalico/calico.org"
     "/Users/gregory.ganley/org-roam/sites/github.com/prometheus/blackbox_exporter/blob/master/example.yml.org"
     "/Users/gregory.ganley/org-roam/sites/github.com/prometheus/blackbox_exporter.org"
     "/Users/gregory.ganley/org-roam/sites/github.com/roboll/helmfile.org"
     "/Users/gregory.ganley/org-roam/sites/github.com/rougier/emacs-gtd.org"
     "/Users/gregory.ganley/org-roam/sites/github.com/sensu-plugins/sensu-plugins-java/tree/0b2d25bd05aa4bf1f341fccfddb2ca0217e45d65/bin.org"
     "/Users/gregory.ganley/org-roam/sites/github.com/sensu-plugins/sensu-plugins-mysql/blob/master/bin/metrics-mysql-graphite.rb.org"
     "/Users/gregory.ganley/org-roam/sites/github.com/sensu-plugins/sensu-plugins-process-checks/commit/c812d0cb7424cd1c3545682ebfc77557d76b555ddiff-3a575ff113ad869187f0b9d4e0edf392e1ba16de100ef8d35e2dca99a30d0de6.org"
     "/Users/gregory.ganley/org-roam/sites/github.com/sensu-plugins/sensu-plugins-process-checks/tree/132862e52c0d457721785eb44725d068e13708fd.org"
     "/Users/gregory.ganley/org-roam/sites/github.com/sensu/sensu-community-plugins/blob/f807971cee35bfc59f2217073f1cca25f7236e2e/plugins/processes/check-procs.rb.org"
     "/Users/gregory.ganley/org-roam/sites/github.com/stedolan/jq/issues/884.org"
     "/Users/gregory.ganley/org-roam/sites/github.com/thanos-io/thanos.org"
     "/Users/gregory.ganley/org-roam/sites/github.com/uswitch/kiam.org"
     "/Users/gregory.ganley/org-roam/sites/github.com/weaveworks/weave.org"
     "/Users/gregory.ganley/org-roam/sites/github.com/hlissner.org"
     "/Users/gregory.ganley/org-roam/sites/github.com/index.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/gitlab-org/gitlab/-/issues/29020.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/gitlab-org/gitlab/-/issues/374001.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/gitlab-org/cli.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/HAT/-/issues/17.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/HAT/-/issues/18.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/HAT/-/issues/19.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/HAT/-/issues/25.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/HAT/-/issues/27.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/HAT/-/merge_requests/2.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/HAT/-/merge_requests/20.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/HAT/-/merge_requests/3.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/HAT/-/merge_requests/4.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/chef-repo/-/issues/1.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/clusters/circus/-/issues/10.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/clusters/circus/-/issues/11.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/clusters/circus/-/issues/14.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/clusters/circus/-/issues/3.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/clusters/circus/-/issues/7.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/clusters/circus/-/issues/9.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/clusters/circus.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/devops/-/issues/48.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/devops/-/issues/52.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/devops/-/issues/54.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/devops/-/issues/55.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/devops/-/issues/56.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/eks-deploy/-/issues/11.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/eks-deploy/-/issues/13.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/eks-deploy/-/issues/15.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/eks-deploy/-/issues/22.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/eks-deploy/-/issues/33.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/eks-deploy/-/issues/36.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/eks-deploy/-/issues/43.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/eks-deploy/-/issues/54.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/eks-deploy/-/issues/57.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/eks-deploy/-/issues/67.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/eks-deploy/-/issues/68.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/eks-deploy/-/merge_requests/12.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/eks-deploy/-/merge_requests/5.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/eks-deploy/-/merge_requests/6.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/eks-deploy/-/labels.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/issues/-/issues/11.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/issues/-/issues/14.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/issues/-/issues/15.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/issues/-/issues/18.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/issues/-/issues/19.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/issues/-/issues/20.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/issues/-/issues/21.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/issues/-/issues/31.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/issues/-/issues/32.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/issues/-/issues/47.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/issues/-/issues/50.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/issues/-/issues/6.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/issues/-/issues/7.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/issues/-/issues/9.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/k8s/helm-chronograf/-/issues/1.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/k8s/helm-grafana/-/issues/1.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/k8s/helm-prometheus-adapter/-/issues/1.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/k8s/helm-prometheus-application/-/issues/3.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/mysql-migrations/-/issues/1.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/terraform/vpc/-/issues/1.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/terraform/vpc/-/issues/2.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/terraform/vpc.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/arbiter.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/depot.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/devops/eks-deploy.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/docs/Library/-/wikis/cloud.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/serverless/domains/-/issues/45.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/website/gatsby-theme-sitespark/-/issues/1.org"
     "/Users/gregory.ganley/org-roam/sites/gitlab.com/racepointenergy/website/support.org"
     "/Users/gregory.ganley/org-roam/sites/go.dev/blog/vuln.org"
     "/Users/gregory.ganley/org-roam/sites/golang.org/pkg/crypto/cipher.org"
     "/Users/gregory.ganley/org-roam/sites/grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/database.org"
     "/Users/gregory.ganley/org-roam/sites/helm.sh/docs/chart_best_practices/templates.org"
     "/Users/gregory.ganley/org-roam/sites/helm.sh/docs/chart_template_guide/accessing_files/configmap-and-secrets-utility-functions.org"
     "/Users/gregory.ganley/org-roam/sites/helm.sh/docs/chart_template_guide/function_list/coalesce.org"
     "/Users/gregory.ganley/org-roam/sites/helm.sh/docs/chart_template_guide/values_files/deleting-a-default-key.org"
     "/Users/gregory.ganley/org-roam/sites/helm.sh/docs/chart_template_guide/named_templates.org"
     "/Users/gregory.ganley/org-roam/sites/helm.sh/docs/helm/helm_template.org"
     "/Users/gregory.ganley/org-roam/sites/helm.sh/helm.sh.org"
     "/Users/gregory.ganley/org-roam/sites/istio.io/latest/docs/concepts/security/authentication.org"
     "/Users/gregory.ganley/org-roam/sites/istio.io/latest/docs/ops/deployment/performance-and-scalability.org"
     "/Users/gregory.ganley/org-roam/sites/istio.io/latest/docs/ops/integrations/certmanager.org"
     "/Users/gregory.ganley/org-roam/sites/istio.io/latest/docs/reference/config/metrics.org"
     "/Users/gregory.ganley/org-roam/sites/istio.io/latest/docs/tasks/security/authorization/authz-custom.org"
     "/Users/gregory.ganley/org-roam/sites/istio.io/index.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes-csi.github.io/docs.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/concepts/configuration/secret.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/concepts/extend-kubernetes/operator.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/kubernetes-objects.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/object-spec-and-status.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/understanding-kubernetes-objects.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/concepts/overview/working-with-objects/names/path-segment-names.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/concepts/overview/working-with-objects/labels.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/concepts/overview/working-with-objects/namespaces.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/concepts/policy/limit-range.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/concepts/policy/resource-quotas.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/concepts/services-networking/service.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/concepts/workloads/controllers/daemonset.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/concepts/workloads/controllers/deployment.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/concepts/workloads/controllers/replicaset.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/concepts/workloads/controllers/statefulset.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/concepts/workloads/pods.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/concepts/scheduling-eviction.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/concepts/services-networking.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/concepts/storage.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/reference/access-authn-authz/rbac/aggregated-clusterroles.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/reference/access-authn-authz/rbac/default-roles-and-role-bindings.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/reference/access-authn-authz/rbac/referring-to-resources.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/reference/access-authn-authz/rbac/referring-to-subjects.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/reference/access-authn-authz/rbac/role-and-clusterrole.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/reference/access-authn-authz/rbac/rolebinding-and-clusterrolebinding.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/reference/access-authn-authz/rbac/user-facing-roles.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/reference/access-authn-authz/admission-controllers.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/reference/access-authn-authz/authentication.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/reference/access-authn-authz/rbac.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/reference/command-line-tools-reference/kubelet.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/reference/kubectl/overview.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/reference/using-api/#api-groups.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/tasks/configure-pod-container/configure-service-account.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/docs/reference.org"
     "/Users/gregory.ganley/org-roam/sites/kubernetes.io/index.org"
     "/Users/gregory.ganley/org-roam/sites/learning.oreilly.com/library/view/istio-up-and/9781492043775/ch01.html#the_value_of_a_service_mesh.org"
     "/Users/gregory.ganley/org-roam/sites/learning.oreilly.com/library/view/istio-up-and/9781492043775.org"
     "/Users/gregory.ganley/org-roam/sites/learning.oreilly.com/library/view/kubernetes-operators/9781492048039.org"
     "/Users/gregory.ganley/org-roam/sites/learning.oreilly.com/library/view/kubernetes-up-and/9781492046523.org"
     "/Users/gregory.ganley/org-roam/sites/learning.oreilly.com/library/view/learning-helm/9781492083641.org"
     "/Users/gregory.ganley/org-roam/sites/learning.oreilly.com/library/view/programming-kubernetes/9781492047094.org"
     "/Users/gregory.ganley/org-roam/sites/magit.vc/index.org"
     "/Users/gregory.ganley/org-roam/sites/medium.com/@cfatechblog/edge-computing-at-chick-fil-a-7d67242675e2.org"
     "/Users/gregory.ganley/org-roam/sites/medium.com/@cfatechblog/site-reliability-engineering-at-chick-fil-a-17bb7c7df6a7.org"
     "/Users/gregory.ganley/org-roam/sites/medium.com/pinterest-engineering/how-to-review-code-as-a-junior-developer-10ffb7846958.org"
     "/Users/gregory.ganley/org-roam/sites/orgmode.org/org.org"
     "/Users/gregory.ganley/org-roam/sites/pkg.go.dev/io#MultiWriter.org"
     "/Users/gregory.ganley/org-roam/sites/platformers.dev/log/2022/authenticate-to-aws-from-gitlab-with-oidc.org"
     "/Users/gregory.ganley/org-roam/sites/postgres-operator.readthedocs.io/en/latest.org"
     "/Users/gregory.ganley/org-roam/sites/promcon.io/2019-munich/slides/containing-your-cardinality.pdf.org"
     "/Users/gregory.ganley/org-roam/sites/prometheus.io/docs/instrumenting/writing_exporters.org"
     "/Users/gregory.ganley/org-roam/sites/prometheus.io/docs/introduction/faq/#why-do-you-pull-rather-than-push.org"
     "/Users/gregory.ganley/org-roam/sites/prometheus.io/docs/prometheus/latest/configuration/alerting_rules.org"
     "/Users/gregory.ganley/org-roam/sites/prometheus.io/index.org"
     "/Users/gregory.ganley/org-roam/sites/registry.terraform.io/providers/hashicorp/aws/latest/docs#assume-role.org"
     "/Users/gregory.ganley/org-roam/sites/scratch99.com/web-development/javascript/how-to-get-the-domain-from-a-url/how_to_get_the_domain_from_a_url_using_javascript_scratch99_design.org"
     "/Users/gregory.ganley/org-roam/sites/shongsdu.github.io/TechChaseWeb.org"
     "/Users/gregory.ganley/org-roam/sites/spinnaker.io/index.org"
     "/Users/gregory.ganley/org-roam/sites/sre.google/sre-book/service-level-objectives.org"
     "/Users/gregory.ganley/org-roam/sites/stackoverflow.com/questions/45821144/minimal-kms-permissions-to-copy-a-database-snapshot/66783986#66783986.org"
     "/Users/gregory.ganley/org-roam/sites/stackoverflow.com/index.org"
     "/Users/gregory.ganley/org-roam/sites/til.hashrocket.com/posts/uv0bjiokwk-use-jq-to-filter-objects-list-with-regex.org"
     "/Users/gregory.ganley/org-roam/sites/tldrlegal.com/tldrlegal.com.org"
     "/Users/gregory.ganley/org-roam/sites/us-west-2.console.aws.amazon.com/amazon_eventbridge.org"
     "/Users/gregory.ganley/org-roam/sites/wiki.savant.com/display/ENG/Savant.com+Website+Infrastructure.org"
     "/Users/gregory.ganley/org-roam/sites/www.chef.io/index.org"
     "/Users/gregory.ganley/org-roam/sites/www.docker.com/index.org"
     "/Users/gregory.ganley/org-roam/sites/www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/header_sanitizing#config-http-conn-man-header-sanitizing.org"
     "/Users/gregory.ganley/org-roam/sites/www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/http_conn_man#config-http-conn-man.org"
     "/Users/gregory.ganley/org-roam/sites/www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http.org"
     "/Users/gregory.ganley/org-roam/sites/www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/http/http_routing#arch-overview-http-routing.org"
     "/Users/gregory.ganley/org-roam/sites/www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/listeners/listeners.org"
     "/Users/gregory.ganley/org-roam/sites/www.envoyproxy.io/www.envoyproxy.io.org"
     "/Users/gregory.ganley/org-roam/sites/www.fredrikholmqvist.com/posts/why-erlang.org"
     "/Users/gregory.ganley/org-roam/sites/www.iana.org/domains/reserved.org"
     "/Users/gregory.ganley/org-roam/sites/www.mail-archive.com/prometheus-users@googlegroups.com/msg04865.org"
     "/Users/gregory.ganley/org-roam/sites/www.notion.so/integrations/gitlab-e719abb7-effd-42f1-aa3f-0f449710fdc0.org"
     "/Users/gregory.ganley/org-roam/sites/www.openpolicyagent.org/www.openpolicyagent.org.org"
     "/Users/gregory.ganley/org-roam/sites/www.orgroam.com/manual.html#Daily_002dnotes/org_roam_user_manual.org"
     "/Users/gregory.ganley/org-roam/sites/www.postgresql.org/docs/current/auth-pg-hba-conf.org"
     "/Users/gregory.ganley/org-roam/sites/www.prometheus.io/docs/prometheus/latest/configuration/recording_rules/recording-rules.org"
     "/Users/gregory.ganley/org-roam/sites/www.redhat.com/sysadmin/podman-mac-machine-architecture.org"
     "/Users/gregory.ganley/org-roam/sites/www.serverless.com/framework/docs/providers/aws/events/schedule.org"
     "/Users/gregory.ganley/org-roam/sites/www.serverless.com/framework/docs/providers/aws/guide/serverless.yml.org"
     "/Users/gregory.ganley/org-roam/sites/www.youtube.com/c/Level1Techs.org"
     "/Users/gregory.ganley/org-roam/sites/www.youtube.com/watch?v=g20Uv6LXAoA.org"
     "/Users/gregory.ganley/org-roam/sites/www.youtube.com/watchv0jUSEfHbTYk.org"
     "/Users/gregory.ganley/org-roam/sites/www.youtube.com/watchv1X3JgCnRNsw.org"
     "/Users/gregory.ganley/org-roam/sites/www.youtube.com/watchvMcY1od_dFoM.org"
     "/Users/gregory.ganley/org-roam/sites/www.youtube.com/watchvg20Uv6LXAoA.org"
     "/Users/gregory.ganley/org-roam/sites/www.zscaler.com/products/zscaler-internet-access.org"
     "/Users/gregory.ganley/org-roam/sites/zenlasopa142.weebly.com/expose-host-gpu-to-docker-container-on-mac.org"
     "/Users/gregory.ganley/org-roam/journal.org"
     "/Users/gregory.ganley/org-roam/notes.org"
     "/Users/gregory.ganley/org-roam/projects.org"))
 '(package-selected-packages
   '(adoc-mode elm-mode emacsql-sqlite-builtin flycheck-elm kubernetes-evil
     magit-delta mustache-mode org-super-agenda ox-asciidoc sops undo-fu-session))
 '(projectile-project-root-files-bottom-up '(".ccls-root" ".projectile" ".git"))
 '(safe-local-variable-values
   '((org-src-preserve-indentation) (eval require 'ox-texinfo+ nil t)
     (eval require 'ol-info)
     (elisp-lint-indent-specs (describe . 1) (it . 1) (thread-first . 0)
      (cl-flet . 1) (cl-flet* . 1) (org-element-map . defun)
      (org-roam-dolist-with-progress . 2) (org-roam-with-temp-buffer . 1)
      (org-with-point-at . 1) (magit-insert-section . defun)
      (magit-section-case . 0) (org-roam-with-file . 2))
     (elisp-lint-ignored-validators "byte-compile" "package-lint"))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ts-fold-replacement-face ((t (:foreground unspecified :box nil :inherit font-lock-comment-face :weight light)))))
(put 'customize-face 'disabled nil)
